### ISSUE TITLE
Can't add multiple GTFS feeds

### ISSUE THREAD

**Issue by modelstudent101** [mark1foley/ha-gtfs-rt-v2#24]
Thanks for such great work. I was hoping to add multiple GTFS feeds, as my transit provider has different feeds for different services.

I've added multiple entries of the sensor to my configuration.yaml, but only the last sensor is created; I can add several stopids/routes if there's a single GTFS feed, but I can't create a second GTFS service.

I can do an easy work-around by creating a second platform, so not a big deal, but I'm guessing this may be an issue for others. In the example below, a sensor for Metro_C is the only one created.

```
# GTFS-v2
sensor:
  - platform: gtfs_rt
    trip_update_url: !secret metro_1
    vehicle_position_url: !secret metro_1
    x_api_key: !secret metro_api_key
    route_delimiter: -
    departures:
    - name: 'Metro_A'
      route: 'A'
      stopid: '1'
      icon: mdi:train
      service_type: train
    - name: 'Metro_B'
      route: 'B'
      stopid: '1'
      icon: mdi:train
      service_type: train
      
sensor:
  - platform: gtfs_rt
    trip_update_url: !secret metro_2
    vehicle_position_url: !secret metro_2
    x_api_key: !secret metro_api_key
    departures:
    - name: 'Metro_C'
      route: 'C'
      stopid: '1'
      icon: mdi:train
      service_type: train
```
