### ISSUE TITLE
Denver RTD - google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by thejevans** [mark1foley/ha-gtfs-rt-v2#35]
# log

https://pastebin.com/UgYPJKdW

# setup 

Home Assistant OS as VM in Proxmox

# relevant config

```yaml
sensor:
 - platform: gtfs_rt
    trip_update_url: "https://www.rtd-denver.com/files/gtfs-rt/TripUpdate.pb"
    vehicle_position_url: "https://www.rtd-denver.com/files/gtfs-rt/VehiclePosition.pb"
    #route_delimiter: "-"
    departures:
      - name: E from Alameda Station to University of Denver
        route: 101E
        stopid: 23060
        icon: mdi:tram
        service_type: Tram
      - name: H from Alameda Station to University of Denver
        route: 101H
        stopid: 23060
        icon: mdi:tram
        service_type: Tram
      - name: D from Alameda Station to 18th & California
        route: 101D
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
      - name: E from Alameda Station to Union Station
        route: 101E
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
      - name: H from Alameda Station to 18th & California
        route: 101H
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
      - name: E from University of Denver to Alameda Station
        route: 101E
        stopid: 34014
        icon: mdi:tram
        service_type: Tram
      - name: H from University of Denver to Alameda Station
        route: 101H
        stopid: 34014
        icon: mdi:tram
        service_type: Tram
      - name: E Southeast
        route: 101E
        stopid: 23060
        icon: mdi:tram
        service_type: Tram
      - name: H Southeast
        route: 101H
        stopid: 23060
        icon: mdi:tram
        service_type: Tram
      - name: D Northwest
        route: 101D
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
      - name: E Northwest
        route: 101E
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
      - name: H Northwest
        route: 101H
        stopid: 23042
        icon: mdi:tram
        service_type: Tram
```
