### ISSUE TITLE
Adding x_api_key header back?

### ISSUE THREAD

**Issue by ollie4452** [mark1foley/ha-gtfs-rt-v2#7]
Hi,

I've noticed that you removed the ability to set x_api_key in the header request when forking from @zacs. However, some providers require it (e.g. the MTA in New York City).  Would you be able to add it back? I'm happy to send a pull request with a fix and updated doc; it would enable something like this to work:

```yaml
# Example entry for New York City, USA
# Notes:
#   * The MTA provides different URLs depending on the subway lines. The one below
#     is for the A, C and E lines.
#   * The API key is required. Get one on the MTA developer web site.
#   * To locate your stopid, go to https://transitfeeds.com/, search for
#     NYC Subway GTFS, pick the most recent date, and open the stops.txt file
#     that lists all the subway stops and their IDs.
sensor:
  - platform: gtfs_rt
    trip_update_url: 'https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace'
    x_api_key: <your key>
    departures:
      - name: 'A (uptown)'
        route: 'A'
        stopid: 'A31N'
        icon: mdi:subway
        service_type: Subway
```

Thanks.
